name: CI/CD Electron App on version tag

on: 
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env: 
  REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
  REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
  REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
  REACT_APP_AUTH_METADATA_URL: ${{ secrets.REACT_APP_AUTH_METADATA_URL }}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn build

      - name: Build using electron-builder
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


